-- ============================================================
-- ElectroHomeSY - Supabase veritabanı şeması
-- Supabase panelinde: SQL Editor > New query > bu dosyanın tamamını yapıştır > Run
-- Birden fazla kez çalıştırmak güvenlidir.
-- ============================================================

-- ---------- Adminler ----------
create table if not exists public.admins (
    user_id uuid primary key references auth.users(id) on delete cascade,
    email text,
    created_at timestamptz not null default now()
);
alter table public.admins enable row level security;

drop policy if exists "admins_read_self" on public.admins;
create policy "admins_read_self" on public.admins
    for select to authenticated using (user_id = auth.uid());

create or replace function public.is_admin()
returns boolean
language sql stable security definer
set search_path = public
as $$
    select exists (select 1 from public.admins where user_id = auth.uid());
$$;

-- ---------- Ürünler (herkese açık bilgiler) ----------
create table if not exists public.products (
    id bigint generated by default as identity primary key,
    category_id int not null default 3,
    title_ar text not null,
    brand text not null default '',
    sku text not null default '',
    description_ar text not null default '',
    base_price numeric(12,2),
    discount_price numeric(12,2),
    stock_quantity int not null default 0,
    images jsonb not null default '[]'::jsonb,
    youtube_url text not null default '',
    is_featured boolean not null default false,
    is_visible boolean not null default true,
    sort_order int not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
alter table public.products enable row level security;

drop policy if exists "products_public_read" on public.products;
create policy "products_public_read" on public.products
    for select to anon, authenticated using (is_visible or public.is_admin());

drop policy if exists "products_admin_insert" on public.products;
create policy "products_admin_insert" on public.products
    for insert to authenticated with check (public.is_admin());

drop policy if exists "products_admin_update" on public.products;
create policy "products_admin_update" on public.products
    for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "products_admin_delete" on public.products;
create policy "products_admin_delete" on public.products
    for delete to authenticated using (public.is_admin());

-- ---------- Ürün maliyetleri (sadece admin görür) ----------
create table if not exists public.product_costs (
    product_id bigint primary key references public.products(id) on delete cascade,
    cost_price numeric(12,2) not null default 0
);
alter table public.product_costs enable row level security;

drop policy if exists "product_costs_admin_all" on public.product_costs;
create policy "product_costs_admin_all" on public.product_costs
    for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ---------- Siparişler ----------
create table if not exists public.orders (
    id bigint generated always as identity primary key,
    created_at timestamptz not null default now(),
    customer_name text not null,
    customer_phone text not null,
    delivery_address text not null default '',
    payment_method text not null default 'cash',
    total_amount numeric(12,2) not null default 0,
    items jsonb not null default '[]'::jsonb,
    status text not null default 'new'
        check (status in ('new', 'confirmed', 'shipped', 'delivered', 'cancelled')),
    admin_note text not null default ''
);
alter table public.orders enable row level security;

-- Ziyaretçiler sadece yeni sipariş ekleyebilir; okuyamaz/değiştiremez.
drop policy if exists "orders_public_insert" on public.orders;
create policy "orders_public_insert" on public.orders
    for insert to anon, authenticated
    with check (status = 'new' and admin_note = '' and length(customer_name) < 200 and length(customer_phone) < 40);

drop policy if exists "orders_admin_select" on public.orders;
create policy "orders_admin_select" on public.orders
    for select to authenticated using (public.is_admin());

drop policy if exists "orders_admin_update" on public.orders;
create policy "orders_admin_update" on public.orders
    for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "orders_admin_delete" on public.orders;
create policy "orders_admin_delete" on public.orders
    for delete to authenticated using (public.is_admin());

-- ---------- Özel ürün talepleri ----------
create table if not exists public.product_requests (
    id bigint generated always as identity primary key,
    created_at timestamptz not null default now(),
    customer_name text not null,
    customer_phone text not null,
    requested_product text not null,
    notes text not null default '',
    is_done boolean not null default false
);
alter table public.product_requests enable row level security;

drop policy if exists "requests_public_insert" on public.product_requests;
create policy "requests_public_insert" on public.product_requests
    for insert to anon, authenticated
    with check (is_done = false and length(requested_product) < 1000);

drop policy if exists "requests_admin_select" on public.product_requests;
create policy "requests_admin_select" on public.product_requests
    for select to authenticated using (public.is_admin());

drop policy if exists "requests_admin_update" on public.product_requests;
create policy "requests_admin_update" on public.product_requests
    for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "requests_admin_delete" on public.product_requests;
create policy "requests_admin_delete" on public.product_requests
    for delete to authenticated using (public.is_admin());

-- ---------- updated_at otomatik güncelleme ----------
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists products_touch_updated_at on public.products;
create trigger products_touch_updated_at
    before update on public.products
    for each row execute function public.touch_updated_at();

-- ---------- Ürün görselleri için depolama alanı ----------
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

drop policy if exists "product_images_admin_insert" on storage.objects;
create policy "product_images_admin_insert" on storage.objects
    for insert to authenticated with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists "product_images_admin_update" on storage.objects;
create policy "product_images_admin_update" on storage.objects
    for update to authenticated using (bucket_id = 'product-images' and public.is_admin());

drop policy if exists "product_images_admin_delete" on storage.objects;
create policy "product_images_admin_delete" on storage.objects
    for delete to authenticated using (bucket_id = 'product-images' and public.is_admin());

-- ---------- İçe aktarmadan sonra ürün numarası sayacını düzelt ----------
create or replace function public.sync_products_id_seq()
returns void
language plpgsql security definer
set search_path = public
as $$
begin
    if not public.is_admin() then
        raise exception 'not allowed';
    end if;
    perform setval(pg_get_serial_sequence('public.products', 'id'), (select coalesce(max(id), 1) from public.products));
end;
$$;
revoke all on function public.sync_products_id_seq() from public, anon;
grant execute on function public.sync_products_id_seq() to authenticated;
